<?php

/**
 * Template for displaying video post format content **** Generated by CHatGPT ****
 *
 * @package portfolioMrMas
 */

// Exit if accessed directly.
if (! defined('ABSPATH')) {
    exit;
}

?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
    <header class="entry-header text-center  background-image style=" background-image: url(<?php echo portfolioMrMas_get_attachment(); ?>);"">
        <?php
        if (is_singular()) :
            the_title('<h1 class="entry-title">', '</h1>');
        else :
            the_title('<h1 class="entry-title"><a href="' . esc_url(get_permalink()) . '" rel="bookmark">', '</a></h1>');
        endif;
        ?>

        <div class="entry-meta">
            <?php echo portfolioMrMas_posted_meta(); ?>
        </div><!-- .entry-meta -->
    </header><!-- .entry-header -->

    <div class="entry-content">
        <?php the_content(); ?>
    </div><!-- .entry-content -->

    <footer class="entry-footer">
        <?php echo portfolioMrMas_posted_footer(); ?>
    </footer><!-- .entry-footer -->
</article><!-- #post -->